 
infer_video:
  min_face_area: 0.1
  bbox_threshold: 0.7
  required_images: 10
  validation_threshold: 0.7
  is_anti_spoof: False
  anti_spoof_threshold: 0.9
  qscore_threshold: 0.4

identity_person:
  l2_threshold: 27.5
  cosine_threshold: 0.75
  distance_mode: 'cosine'
  qscore_collect_threshold: 0.5
  image_per_class: 3
  

