 
infer_video:
  min_face_area: 0.1
  bbox_threshold: 0.7
  required_images: 5
  validation_threshold: 0.7
  is_anti_spoof: True
  distance_mode: 'cosine'
  anti_spoof_threshold: 0.9

identity_person:
  l2_threshold: 27.5
  cosine_threshold: 0.8
  distance_mode: 'cosine'


collect_data:
  min_face_area: 10000
  bbox_threshold: 0.6
  required_images: 30
  is_anti_spoof: True
  anti_spoof_threshold: 0.95