name: "ultralight"
platform: "onnxruntime_onnx"
default_model_filename: "version-RFB-640-dynamic.onnx"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 480, 640]
  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [17640, 2]
  },
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [17640, 4]
  }
]
instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
dynamic_batching {
  preferred_batch_size: [4, 8, 16]
  max_queue_delay_microseconds: 1000
}
